name: deploy to lambda

on:
  push: 
    branches:
      - "master"
  workflow_dispatch:

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: cd lambda && npm ci
      - name: zip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r ./bundle.zip ./lambda/
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          function_name: store-hash
          zip_file: bundle.zip